openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of contacts app
tags:
  - name: User
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Water
    description: Operations about Waters.
servers:
  - url: http://localhost:3000
  - url: https://bo-o-woa.onrender.com
paths:
  /user:
    get:
      $ref: ../swagger/paths/user/get.yaml
  /user/updata:
    patch:
      $ref: ../swagger/paths/user/patchupdata.yaml
  /user/avatar:
    patch:
      $ref: ../swagger/paths/user/patchavatar.yaml
  /user/daily:
    patch:
      $ref: ../swagger/paths/user/patchdaily.yaml
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signup/post.yaml
  /auth/signin:
    post:
      $ref: ../swagger/paths/auth/signin/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /water/daily:
    get:
      $ref: ../swagger/paths/water/getdaily.yaml
  /water/monthly:
    get:
      $ref: ../swagger/paths/water/getmonthly.yaml
  /water/glass:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{glassId}:
    patch:
      $ref: ../swagger/paths/water/patch.yaml
  /water/glass/{glassId}:
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer